# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Book.destroy_all
User.destroy_all

user1 = User.create(first_name: "Ava", last_name: "Taylor", location: "Hackney", email: "ava.taylor@yahoo.com", password: '123123', password_confirmation: '123123')
user2 = User.create(first_name: "Liam", last_name: "Smith", location: "Camden", email: "liam.smith@gmail.com", password: '123123', password_confirmation: '123123')
user3 = User.create(first_name: "Olivia", last_name: "Brown", location: "Islington", email: "olivia.brown@hotmail.com", password: '123123', password_confirmation: '123123')
user4 = User.create(first_name: "Noah", last_name: "Johnson", location: "Westminster", email: "noah.johnson@outlook.com", password: '123123', password_confirmation: '123123')
user5 = User.create(first_name: "Sophia", last_name: "Williams", location: "Kensington", email: "sophia.williams@icloud.com", password: '123123', password_confirmation: '123123')
user6 = User.create(first_name: "James", last_name: "Jones", location: "Brixton", email: "james.jones@yahoo.com", password: '123123', password_confirmation: '123123')
user7 = User.create(first_name: "Emily", last_name: "Davis", location: "Clapham", email: "emily.davis@gmail.com", password: '123123', password_confirmation: '123123')
user8 = User.create(first_name: "Benjamin", last_name: "Miller", location: "Shoreditch", email: "benjamin.miller@hotmail.com", password: '123123', password_confirmation: '123123')
user9 = User.create(first_name: "Charlotte", last_name: "Wilson", location: "Chelsea", email: "charlotte.wilson@outlook.com", password: '123123', password_confirmation: '123123')
user10 = User.create(first_name: "Henry", last_name: "Moore", location: "Greenwich", email: "henry.moore@icloud.com", password: '123123', password_confirmation: '123123')
user11 = User.create(first_name: "Amelia", last_name: "Taylor", location: "Hackney", email: "amelia.taylor@gmail.com", password: '123123', password_confirmation: '123123')
user12 = User.create(first_name: "Jack", last_name: "Thomas", location: "Bermondsey", email: "jack.thomas@yahoo.com", password: '123123', password_confirmation: '123123')
user13 = User.create(first_name: "Isabella", last_name: "White", location: "Hammersmith", email: "isabella.white@hotmail.com", password: '123123', password_confirmation: '123123')
user14 = User.create(first_name: "Lucas", last_name: "Clark", location: "Tower Hamlets", email: "lucas.clark@outlook.com", password: '123123', password_confirmation: '123123')
user15 = User.create(first_name: "Mia", last_name: "Harris", location: "Richmond", email: "mia.harris@gmail.com", password: '123123', password_confirmation: '123123')
user16 = User.create(first_name: "Alexander", last_name: "Lewis", location: "Fulham", email: "alexander.lewis@icloud.com", password: '123123', password_confirmation: '123123')
user17 = User.create(first_name: "Grace", last_name: "Walker", location: "Wandsworth", email: "grace.walker@yahoo.com", password: '123123', password_confirmation: '123123')
user18 = User.create(first_name: "Ethan", last_name: "Scott", location: "Paddington", email: "ethan.scott@hotmail.com", password: '123123', password_confirmation: '123123')
user19 = User.create(first_name: "Harper", last_name: "Green", location: "Lewisham", email: "harper.green@outlook.com", password: '123123', password_confirmation: '123123')
user20 = User.create(first_name: "Daniel", last_name: "Baker", location: "Croydon", email: "daniel.baker@gmail.com", password: '123123', password_confirmation: '123123')

book1 = Book.create(title: "The Great Gatsby", author: "F. Scott Fitzgerald", genre: "Classic", publish_date: 1925, user: user1)
book2 = Book.create(title: "To Kill a Mockingbird", author: "Harper Lee", genre: "Classic", publish_date: 1960, user: user2)
book3 = Book.create(title: "1984", author: "George Orwell", genre: "Classic", publish_date: 1949, user: user3)
book4 = Book.create(title: "Pride and Prejudice", author: "Jane Austen", genre: "Classic", publish_date: 1813, user: user4)
book5 = Book.create(title: "The Catcher in the Rye", author: "J.D. Salinger", genre: "Classic", publish_date: 1951, user: user3)
book6 = Book.create(title: "The Bell Jar", author: "Sylvia Plath", genre: "Classic", publish_date: 1963, user: user5)
book7 = Book.create(title: "The Picture of Dorian Gray", author: "Oscar Wilde", genre: "Classic", publish_date: 1890, user: user6)
book8 = Book.create(title: "The Hobbit", author: "J.R.R. Tolkien", genre: "Fantasy", publish_date: 1937, user: user7)
book9 = Book.create(title: "Harry Potter and the Philosopher's Stone", author: "J.K. Rowling", genre: "Fantasy", publish_date: 1997, user: user8)
book10 = Book.create(title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis", genre: "Fantasy", publish_date: 1950, user: user9)
book11 = Book.create(title: "The Hunger Games", author: "Suzanne Collins", genre: "Fantasy", publish_date: 2008, user: user10)
book12 = Book.create(title: "The Fellowship of the Ring", author: "J.R.R. Tolkien", genre: "Fantasy", publish_date: 1954, user: user11)
book13 = Book.create(title: "Moby Dick", author: "Herman Melville", genre: "Adventure", publish_date: 1851, user: user1)
book14 = Book.create(title: "Brave New World", author: "Aldous Huxley", genre: "Dystopian", publish_date: 1932, user: user2)
book15 = Book.create(title: "War and Peace", author: "Leo Tolstoy", genre: "Historical Fiction", publish_date: 1869, user: user12)
book16 = Book.create(title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", genre: "Philosophical Fiction", publish_date: 1880, user: user13)
book17 = Book.create(title: "Crime and Punishment", author: "Fyodor Dostoevsky", genre: "Psychological Fiction", publish_date: 1866, user: user13)
book18 = Book.create(title: "Frankenstein", author: "Mary Shelley", genre: "Gothic", publish_date: 1818, user: user14)
book19 = Book.create(title: "The Grapes of Wrath", author: "John Steinbeck", genre: "Historical Fiction", publish_date: 1939, user: user15)
book20 = Book.create(title: "Wuthering Heights", author: "Emily Brontë", genre: "Gothic Romance", publish_date: 1847, user: user7)
book21 = Book.create(title: "The Alchemist", author: "Paulo Coelho", genre: "Adventure Fiction", publish_date: 1988, user: user8)
book22 = Book.create(title: "The Road", author: "Cormac McCarthy", genre: "Post-Apocalyptic Fiction", publish_date: 2006, user: user16)
book23 = Book.create(title: "Anna Karenina", author: "Leo Tolstoy", genre: "Romance", publish_date: "1877", user: user17)
book24 = Book.create(title: "Jane Eyre", author: "Charlotte Brontë", genre: "Gothic Fiction", publish_date: 1847, user: user19)
book25 = Book.create(title: "Fifty Shades of Grey", author: "E.L. James", genre: "Romance", publish_date: 2012, user: user18)
book26 = Book.create(title: "Fahrenheit 451", author: "Ray Bradbury", genre: "Dystopian", publish_date: 1953, user: user19)
book27 = Book.create(title: "The Stranger", author: "Albert Camus", genre: "Philosophical Fiction", publish_date: 1942, user: user20)
book28 = Book.create(title: "One Hundred Years of Solitude", author: "Gabriel García Márquez", genre: "Magical Realism", publish_date: 1967, user: user7)
book29 = Book.create(title: "Dracula", author: "Bram Stoker", genre: "Gothic Horror", publish_date: 1897, user: user20)
book30 = Book.create(title: "The Eyre Affair", author: "Jasper Fforde", genre: "Science Fiction", publish_date: 2001, user: user19)
book31 = Book.create(title: "Beloved", author: "Toni Morrison", genre: "Historical Fiction", publish_date: 1987, user: user16)
book32 = Book.create(title: "The Kite Runner", author: "Khaled Hosseini", genre: "Historical Fiction", publish_date: 2003, user: user14)
book33 = Book.create(title: "Gone Girl", author: "Gillian Flynn", genre: "Psychological Fiction", publish_date: 2012, user: user3)
book34 = Book.create(title: "Coraline", author: "Neil Gaiman", genre: "Horror", publish_date: 2002, user: user2)
book35 = Book.create(title: "Never Let Me Go", author: "Kazuo Ishiguro", genre: "Science Fiction", publish_date: 2005, user: user1)
book36 = Book.create(title: "The Curious Incident of the Dog in the Night-Time", author: "Mark Haddon", genre: "Mystery", publish_date: 2003, user: user13)
book37 = Book.create(title: "The Metamorphosis", author: "Franz Kafka", genre: "Absurdist Fiction", publish_date: 1915, user: user5)
book38 = Book.create(title: "The Old Man and the Sea", author: "Ernest Hemingway", genre: "Literary Fiction", publish_date: 1952, user: user9)
book39 = Book.create(title: "The Handmaid's Tale", author: "Margaret Atwood", genre: "Dystopian", publish_date: 1985, user: user10)
book40 = Book.create(title: "Cloud Atlas", author: "David Mitchell", genre: "Science Fiction", publish_date: 2004, user: user11)
book41 = Book.create(title: "The Sun Also Rises", author: "Ernest Hemingway", genre: "Literary Fiction", publish_date: 1926, user: user13)
book42 = Book.create(title: "Mansfield Park", author: "Jane Austen", genre: "Romantic Fiction", publish_date: 1814, user: user1)
book43 = Book.create(title: "The Lovely Bones", author: "Alice Sebold", genre: "Supernatural", publish_date: 2002, user: user3)
book44 = Book.create(title: "The Scarlet Letter", author: "Nathaniel Hawthorne", genre: "Historical Fiction", publish_date: 1850, user: user15)
book45 = Book.create(title: "Catch-22", author: "Joseph Heller", genre: "Satirical Fiction", publish_date: 1961, user: user19)
book46 = Book.create(title: "Northern Lights", author: "Phillip Pullman", genre: "Science Fiction", publish_date: 1995, user: user10)
book47 = Book.create(title: "A Tale of Two Cities", author: "Charles Dickens", genre: "Historical Fiction", publish_date: 1859, user: user2)
book48 = Book.create(title: "The Call of the Wild", author: "Jack London", genre: "Adventure Fiction", publish_date: 1903, user: user1)
book49 = Book.create(title: "The Sound and the Fury", author: "William Faulkner", genre: "Southern Gothic", publish_date: 1929, user: user18)
book50 = Book.create(title: "Misery", author: "Stephen King", genre: "Horror", publish_date: 1987, user: user12)

puts "Seeds created"
